### ISSUE TITLE
Network error prevents installation of packages.

### ISSUE THREAD

**Issue by maxaug** [rdemaria/cmmnbuild_dep_manager#1]
Hello!

I'm trying to get pytimber to work, so far unsuccessfully and I have found this package is causing trouble. When I invoke following code:

```
import cmmnbuild_dep_manager
mgr = cmmnbuild_dep_manager.Manager()
mgr.install('pytimber')
```
The program exits with: 
 `[Errno socket error] [Errno 8]  nodename nor servname provided, or not known`

I dug a little big deeper into the stack and turns out Manager#_get_products() tries to open the url `http://abwww.cern.ch/ap/dist/repository.xml` which seems to be unavailable. 

I'm running anaconda python 2.7 on os x 10.11.

**Comment by rdemaria** [comment]
You need to be on the cern network to access the packages in abww.cern.ch. Please send me a message to my cern email such that we can discuss offline.

**Comment by levens** [comment]
Hi Max,

As you found out, resolution of the jars requires access to http://abwww.cern.ch/.  This is only available from inside the CERN network.

Cheers,
